### ISSUE TITLE
How to run SeqtoSeq trian?

### ISSUE THREAD

**Issue by rainfalj** [UFAL-DSG/tgen#13]
I run as ./run_tgen.py seq2seq_train -d ./debug1 -w ./workdir -e 10 config train-das train-trees seq2seq-model
get error:IOError: [Errno 2] No such file or directory: 'config'
I install pytreex but no treex

**Comment by tuetschek** [comment]
Sorry about the bad documentation, I promise to make it more readable in the coming weeks.

The basic command goes like this:
`./run_tgen.py seq2seq_train <config-file> <train-das-file> <train-trees-file> <out-model-file>`

Note that there are 3 input files required:

- `<config-file>`: configuration file with all the parameters of the generator (example configuration file can be found in this repository in [bagel-data/config/seq2seq.py](https://github.com/UFAL-DSG/tgen/blob/master/bagel-data/config/seq2seq.py) and similarly for other datasets I experiment with.

- `<train-das-file>`: a file with training DAs (see [the Makefile in bagel-data/input](https://github.com/UFAL-DSG/tgen/tree/master/bagel-data/input) for more details on how to convert the BAGEL data set to the right format. I attach an example file [here](https://github.com/UFAL-DSG/tgen/files/535630/toy-das.txt).

- `<train-trees-file>`: a file with training trees or strings. If you didn't install Treex, you probably want to use just strings. In that case, set `mode: 'tokens'` in the configuration file. An example strings file is attached [here](https://github.com/UFAL-DSG/tgen/files/535629/toy-text.txt).

The trained model will be then saved in `<out-model-file>`, and you can use it to generate via the `./run_tgen.py seq2seq_gen [...]` command.

The error message you are getting suggests that didn't pass a valid path to the configuration file.

**Comment by rainfalj** [comment]
Thankyou,I read you paper and get the datasets from https://github.com/UFAL-DSG/alex_context_nlg_dataset. But I don't know how to use this data. How can I convert the alex_context_nlg_dataset into the  input file: das-file, tree-file and context file?

**Comment by tuetschek** [comment]
Again, sorry about the lack of documentation. To prepare the training files for this dataset, use the [Makefile in `alex-context/input`](https://github.com/UFAL-DSG/tgen/blob/master/alex-context/input/Makefile).

Running just `make` would also get you the trees in Treex files (and you would need Treex for that), so run `make train-text.txt` to get all training/testing text files (including `train-text.txt` and `train-das.txt`).

PS: If you're interested in the Alex Context NLG dataset, then you might want to start with the configuration file [`alex-context/config/seq2seq.py`](https://github.com/UFAL-DSG/tgen/blob/master/alex-context/config/seq2seq.py).

**Comment by swanand30** [comment]
Hi, 
I am trying to run the make file in alex-context/input, for that I am using dataset.json . The make file is giving an error as convert.py is not able to import recordclass, and I am unable to find it in the t-gen source code.

Thanks in advance.

**Comment by tuetschek** [comment]
@swanand30: Thank you for your message. [recordclass](https://pypi.python.org/pypi/recordclass) is actually a dependency that I forgot to list on the main page. It is fixed now.
