### ISSUE TITLE
Add more helpful help

### ISSUE THREAD

**Issue by tuetschek** [UFAL-DSG/tgen#14]
There should be a simple tutorial, and the command itself should provide more information on how to proceed

**Comment by rainfalj** [comment]
Thankyou,I read you paper and get the datasets from https://github.com/UFAL-DSG/alex_context_nlg_dataset. But I don't know how to use this data. How can I convert the alex_context_nlg_dataset into the input file: das-file, tree-file and context file?

**Comment by tuetschek** [comment]
I'm very sorry, I must have missed your comment. Use the [alex-context/input/convert.py](https://github.com/UFAL-DSG/tgen/blob/master/alex-context/input/convert.py) script:
```
./convert.py -m -n -s 3:1:1 dataset.json train,devel,test
```

There is now at least some basic usage information in [USAGE.md](https://github.com/UFAL-DSG/tgen/blob/master/USAGE.md).
