### ISSUE TITLE
E2E NLG Challenge

### ISSUE THREAD

**Issue by shubhamagarwal92** [UFAL-DSG/tgen#24]
Hi @tuetschek 
The baseline outputs provided [here](http://www.macs.hw.ac.uk/InteractionLab/E2E/data/baseline-output.txt) are not aligned with the devset. 
I think that there is some random seed which shuffles the data when we pass -m flag to [input/convert.py](https://github.com/UFAL-DSG/tgen/blob/master/e2e-challenge/input/convert.py). 
Could you provide devel-*.txt/sgm for the unshuffled devset so that we could compare our results over the baseline (or provide outputs.txt for unshuffled data).

**Comment by tuetschek** [comment]
Hi @shubhamagarwal92 , thanks for spotting this! You are right, they are not aligned. There is no randomization intended, but when the data is grouped according to the MR, a plain python `dict` is used which does not guarantee ordering. This is a bug – I reused code from another dataset where I couldn't assume ordering according to the MR. I will create a fix and update the generated outputs accordingly.

**Comment by tuetschek** [comment]
I've fixed the problem in ac510e6db090a0cf886c007d6fe3cf013f7e76a7. 

I've uploaded the unshuffled outputs to [the challenge website](http://www.macs.hw.ac.uk/InteractionLab/E2E/data/baseline-output.txt). You can also get the unshuffled [devel-* files here](http://www.macs.hw.ac.uk/InteractionLab/E2E/data/devel-refs.zip).

Hope it works for you now (if not, please let me know). Thanks for reporting this and sorry for the inconvenience.

**Comment by shubhamagarwal92** [comment]
Hi @tuetschek 
Thank you for your help.
I have not looked into the mteval perl script to calculate the BLEU scores. But could you clarify, why don't you pass the source MRs/DAs (devel-conc_das.sgm/txt) in a raw form explicitly (slot1[value1],slot2[value2]) instead of converting it into the form used by tgen (inform(slot=value)). 

Is the MR being used to calculate the BLEU score? 

I am publishing a small code to group the MRs considering they are in a different file (have to put a check for file encoding and special characters):

```
import numpy as np
import os
import sys
import argparse

parser = argparse.ArgumentParser(
    description="Extract unique DAs")
parser.add_argument(
    "--sourceFilePath",
    dest="sourceFilePath",
    type=str,
    help="sourceFilePath")
parser.add_argument(
    "--sourceGroupedFilePath",
    dest="sourceGroupedFilePath",
    type=str,
    help="sourceGroupedFilePath")

with open(sourceFilePath) as sourceFile:
    source = sourceFile.read().splitlines() 

sourceNumpyArray = np.array(source)
_, idx = np.unique(sourceNumpyArray, return_index=True)
sourceNumpyArrayGrouped = sourceNumpyArray[np.sort(idx)]

np.savetxt(sourceGroupedFilePath,sourceNumpyArrayGrouped, fmt="%s")

```

**Comment by tuetschek** [comment]
@shubhamagarwal92 , actually BLEU does not use the source file at all – I'm only passing this file so the Perl script does not crash. It does not matter whether you use the original MR format or TGen's, there can be anything and the score won't change.

I'm planning to integrate running the MT-Eval script into the MSCOCO script and create the sgm files on-the-fly, with the source file being empty.

**Comment by shubhamagarwal92** [comment]
@tuetschek That is what I actually thought so too. 
Thanks for the clarification.
