### ISSUE TITLE
sfx-restaurant step by step

### ISSUE THREAD

**Issue by mOeztuerk** [UFAL-DSG/tgen#37]
Hello,
can you please give a short step by step tutorial on how to use the sfx-restaurant?
I am not sure if I have done the preprocessing and trainig right, because I geht the error:
```
NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint.
Key rerank-/rnn/embedding_wrapper/basic_lstm_cell/bias not found in checkpoint
```

Can this be caused by not having installed Treex?

**Comment by tuetschek** [comment]
As for the how-to, I just created a short [readme](https://github.com/UFAL-DSG/tgen/tree/master/sfx-restaurant) for sfx-restaurant. Hope it helps.

**Comment by mOeztuerk** [comment]
Thank you for your response! The readme helped me a lot and made some steps clear.
I will train and generate overnight and answer tomorrow.

Next step: Is it possible to set up a dialog interface for example in the terminal. Like:
user_input: I want some cheap chinese food.
system_output: The Chinatown-XYZ  is good for chinese and is located at chinatown 123. The phone number is 1234567 and the price range is cheap.
user_input: ok bye.
system_output: goodbye

hope you get what I mean

**Comment by tuetschek** [comment]
@mOeztuerk : I know what you mean, but this amounts to a full dialogue system. You'd need to program language understanding and dialogue management yourself -- TGen can't do that.
