### ISSUE TITLE
sfx-restaurant test output problem

### ISSUE THREAD

**Issue by giobin** [UFAL-DSG/tgen#38]
hello,
I'm trying to train and test your model on the sfx-restaurant dataset.
I'm following your short HOWTO to train the model and test it on development data.
Unfortunately I'm not able to get lexicalized text in the output.txt file. 
If I run `../run_tgen.py seq2seq_gen --eval-file data/devel-ref.txt --abstr-file data/devel-abst.txt  --output-file output.txt model.pickle.gz data/devel-das.txt` I get this results on terminal: 
<img width="916" alt="schermata 2018-09-17 alle 14 24 17" src="https://user-images.githubusercontent.com/3843501/45622786-7f106e00-ba85-11e8-97f7-4d4c2e54c37c.png"> 
The output file shows results like: 

> can i confirm you are seeking option near X-near ?
> the name of the X-type is X-name .

I think I'm missing some stage in the training/test pipeline, but I don't know exactly what.

**Comment by tuetschek** [comment]
Hi, sorry for the delay. I can reproduce this and I'll try to find out what the problem is. (No stage is missing, but there must be some kind of a bug.)

**Comment by tuetschek** [comment]
Should be fixed in https://github.com/UFAL-DSG/tgen/commit/849fc3b73db31954810036416e7feb9c97d08de0 . @giobin please update your checkout and me know if you still have the problem. Thanks for reporting!

**Comment by giobin** [comment]
yes, now it works for me. Thank you!
