### ISSUE TITLE
python 3.7 is not work

### ISSUE THREAD

**Issue by 595972434** [UFAL-DSG/tgen#40]
import cPickle as pickle
ModuleNotFoundError: No module named 'cPickle'

**Comment by 595972434** [comment]
python 2.7 is ok

**Comment by tuetschek** [comment]
@595972434 which file is it?

**Comment by 595972434** [comment]
this file:   tgen/tgen/futil.py
i googled this error, there is no cPickle in python3

**Comment by tuetschek** [comment]
Yes, that's right. I've updated the code to run Python3 pretty recently, and [that line is no longer in that file](https://github.com/UFAL-DSG/tgen/blob/master/tgen/futil.py#L16). Please try pulling from Github and see if the problem persists.
