### ISSUE TITLE
How to run the program?

### ISSUE THREAD

**Issue by kklw** [UFAL-DSG/tgen#6]
Hi. I'm trying to run the **run_tgen.py** script. For the **candgen_train()** function, there are these 3 parameters: 
`fname_da_train, fname_ttrees_train, fname_cand_model `

Is the correct file for **fname_da_train**, **bagel-data/input/toy-das.txt** which is the dialogue acts?
And I guess the **fname_ttrees_train** refers to the deep-syntactic dependency trees from the input meaning representation. It seems like it needs a pickle or yaml file, but I'm not sure which is the exact file it is referring to.

Thanks!

**Comment by tuetschek** [comment]
Yes, you are right – `toy-das.txt` is a correct value for the `fname_da_train` parameter.

For `ttrees-train`, you would need a [Treex](http://ufal.mff.cuni.cz/treex)-analyzed version of the `toy-text.txt` file, saved in the YAML format (it will create a pickle dump on first use to speed up loading). The `Makefile` in the `input/` subdirectory can process it for you – this should be enough if you have Treex installed:

    make toy-text.yaml.gz

I have attached the Treex-processed file here: [toy-text.yaml.gz](https://github.com/UFAL-DSG/tgen/files/204809/toy-text.yaml.gz), so you can just download it and use it. 

But note that the generator itself will only produce similar YAML files containing deep syntax trees. You need Treex to perform surface realization, i.e., convert the trees to normal sentences.

Also note that the files `toy-*` are just a toy example.
