### ISSUE TITLE
TensorFlow 0.7+ compatibility

### ISSUE THREAD

**Issue by tuetschek** [UFAL-DSG/tgen#8]
The current version is apparently only compatible with 0.6

**Comment by tuetschek** [comment]
Since 0.7 breaks my beam search (rnn decoder functions only return the last state, not all states), this requires rewriting the decoder functions. Maybe use NeuralMonkey as a dependency instead?

**Comment by foxik** [comment]
BTW, TensorFlow 1.0 has been out for some time -- as TensorFlow uses semantic versioning, since 1.0 the API is backward-compatible (until version 2.0 comes out).

**Comment by tuetschek** [comment]
I know... you're right, I just have time neither to fix the problem nor to update the issue :-(.

**Comment by foxik** [comment]
BTW, they have a Transitioning guide for 1.0 at https://www.tensorflow.org/install/migration and even a script at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility, but that will not help you with the rnn decoder (although they say it converts 0.n->1.0, it is mostly 0.12->1.0 looking at the source).

**Comment by tuetschek** [comment]
Well, they broke a major feature of my code using their seq2seq functions in 0.7 already... then finished it off in 0.12/1.0 by removing the whole old seq2seq stuff... so I will still need a lot of rewriting/copying their old code anyway. If it was only about renaming a function here and there, it would have long been done.

**Comment by foxik** [comment]
Yeah, the API changes before 1.0 were wild, hopefully that will be better now :-) I like the `dynamic_rnn_decoder` present in 1.0 because it is much easier to work with (because you do not have to do the manual slicing etc of the input, just pass 3D tensor), but it requires a lot of rewriting...

Maybe you could just take the original 0.6 seq2seq stuff and just update it to 1.0 and add it to your project...

**Comment by tuetschek** [comment]
Yes, that's what I'm planning to do, at least initially... I was just too busy with my thesis so far (finished the write-up just a week ago and read it after myself only yesterday :-( ).

**Comment by tuetschek** [comment]
Thanks for the pointer to the new decoder :-)

**Comment by foxik** [comment]
Congrats with the thesis!
